name: 'Custom Action'
description: 'Una acción en la EATI 2023'
inputs:
  location:
    description: "La ubicación para la cual se desea conocer el clima"
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'bookmark'
  color: 'purple'